services:
  zoneminder:
    image: zoneminder2025  # change to the name you used when you build the image !
    container_name: Zoneminder2025
    privileged: true
    shm_size: 8G
    networks:
     # - traefik_proxy
      - default
    ports:
      - '8843:443/tcp'
      - '19099:9000/tcp'
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /opt/zoneminder2025/events:/var/lib/zoneminder/events
      - /opt/zoneminder2025/events:/var/cache/zoneminder/events
      - /opt/zoneminder2025/images:/var/lib/zoneminder/images
      - /opt/zoneminder2025/images:/var/cache/zoneminder/images
      - /opt/zoneminder2025/logs:/var/log/zm
      - /opt/zoneminder2025/config/:/config

