name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    name: Test pull request function
    runs-on: ubuntu-20.4
    environment: playground
    permissions:
     contents: read
     packages: write
    steps:
    # Checkout repository
    - name: Checkout
      uses: actions/checkout@v4

#    - name: Log in to the Container registry
#      uses: docker/login-action@v4
#      with:
#       registry: ${{ env.REGISTRY }}
#       username: ${{ secrets.DOCKERHUB_USERNAME }}
#       password: ${{ secrets.DOCKERHUB_PASSWORD }}

#    - name: Extract metadata (tags, labels) for Docker
#      id: meta
#      uses: docker/metadata-action@v5
#      with:
#       images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

 #   - name: Check variables
 #     run: |
 #       echo 'Current path:'
 #       pwd
 #       echo 'Tag: ${{ steps.meta.outputs.tags }}'
 #       echo 'Label: ${{ steps.meta.labels.tags }}'
